1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [2]:
a1 = a.reshape(2, 6)
print(f'a1={a1}')

a2 = a.reshape(3, 4)
print(f'a2={a2}')

a3 = a.reshape(4, 3)
print(f'a3={a3}')

a4 = a.reshape(6, 2)
print(f'a4={a4}')

a5 = a.reshape(12, 1)
print(f'a5={a5}')

a1=[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
a2=[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a3=[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a4=[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a5=[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [3]:
a11 = a.reshape(2, -1)
print(f'a11={a11}')

a22 = a.reshape(3, -1)
print(f'a22={a22}')

a33 = a.reshape(4, -1)
print(f'a33={a33}')

a44 = a.reshape(-1, 2)
print(f'a44={a44}')

a55 = a.reshape(-1, 1)
print(f'a55={a55}')

a11=[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
a22=[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a33=[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a44=[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a55=[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [4]:
print(f'Да, можно.' if a55.ndim == 1 else f'Нельзя, с точки зрения numpy, a55={a55} - это {a55.ndim}-мерный массив.')

Нельзя, с точки зрения numpy, a55=[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]] - это 2-мерный массив.


5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [5]:
a = np.random.randn(3, 4)
a_fl = a.flatten()
print(a_fl)
print(f'Sizes are equal' if np.size(a) == np.size(a_fl) else f'Sizes are not equal')

[-1.33756165 -0.26030088  0.0474178  -1.11427994  1.01870444 -0.24125927
 -1.2101007   0.19015558 -1.17380025  0.30301287  1.39728496  0.16083293]
Sizes are equal


6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [6]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [7]:
s = np.arange(20, 1, -2)
b = s.reshape(1, -1)
print(b)

print(f'dim(a) = {a.ndim}; dim(b) = {b.ndim}')

[[20 18 16 14 12 10  8  6  4  2]]
dim(a) = 1; dim(b) = 2


8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [8]:
a = np.zeros((2, 2))
print(f'a = {a}')

b = np.ones((3, 2))
print(f'b = {b}')

v = np.vstack((a, b))
print(f'v = {v}')
print(f"v'size = {np.size(v)}")

a = [[0. 0.]
 [0. 0.]]
b = [[1. 1.]
 [1. 1.]
 [1. 1.]]
v = [[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
v'size = 10


9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [9]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.transpose()
B = np.dot(A, At)
print(B)

d = int(np.linalg.det(B))

print(f'B - {B.ndim}-мерная матрица размера {B.shape}.')
print(f'Обратную матрицу к В вычислить нельзя, т.к. определитель В = {d}.' if d == 0 
      else f'Обратную матрицу можно посчитать, т.к. определитель В = {d} (а не 0).')

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
B - 2-мерная матрица размера (4, 4).
Обратную матрицу к В вычислить нельзя, т.к. определитель В = 0.


10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [10]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [11]:
c = np.random.randint(0, 16, size=16)
print(c)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [12]:
C = c.reshape(4, 4)
C = C * 10
D = C + B

d = int(np.linalg.det(D))
r = np.linalg.matrix_rank(D)
if d != 0:
    D_inv = np.linalg.inv(D)
    print(f'D = {D}')
    print(f'Определитель D = {d}')
    print(f'Ранг D = {r}')
    print(f'D_inv = {D_inv}')
else:
    print(f'D = {D}')
    print(f'Обратную матрицу к D вычислить нельзя, т.к. определитель D = {d}. Ранг D = {r}.')

D = [[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]
Определитель D = -28511999
Ранг D = 4
D_inv = [[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [13]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
print(f'D_inv(mask) = {D_inv}\n')

print(f'B = {B}')
print(f'C = {C}\n')

E = np.where(D_inv == 1, B, C)
print(f'E = {E}')

D_inv(mask) = [[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]

B = [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
C = [[ 60  30 120 140]
 [100  70 120  40]
 [ 60  90  20  60]
 [100 100  70  40]]

E = [[  5  14  23 140]
 [100  70 120 122]
 [ 60  90  20 212]
 [ 32 100 212  40]]
